sudo: required

language: android
jdk: oraclejdk8

# safelist
branches:
  only:
  - development

notifications:  #Optional
    email:
        - oleksii.yanushkevych@gmail.com #Add your email address
        - babenkovladimirbmd@gmail.com 

# before_install:
# - pip install --user codecov    #Install codecov

env:
    matrix:
        - ANDROID_TARGET=android-25 ANDROID_ABI=google_apis/armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repositor
    - build-tools-25.0.2
    - android-25
    - add-on
    - sys-img-armeabi-v7a-google_apis-25
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
      
before_script:
  - chmod +x gradlew      #Grand permissions
  - android list targets
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api
  - emulator -avd test -no-audio -no-window &   #Start emulator

script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - android-wait-for-emulator
    - adb devices   #Display list of devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedCheck -PdisablePreDex --stacktrace

before_install:
    - pip install --user codecov    #Install codecov

after_success:
    - codecov                       #Run codecov
