sudo: required

language: android
jdk: oraclejdk8

# safelist
branches:
  only:
  - development

notifications:  #Optional
    email:
        - oleksii.yanushkevych@gmail.com #Add your email address
        - babenkovladimirbmd@gmail.com 

before_install:
- pip install --user codecov    #Install codecov

env:
  global:
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
  - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repositor
    - build-tools-28.0.3
    - android-28

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
      
before_script:
  - chmod +x gradlew

stages:
  - test

unitTests:
  stage: test
  script:
    # - ./gradlew clean build
    - ./gradlew test --stacktrace
    - cat /home/travis/build/PharosProduction/inet-monitor/internetconnectionlibrary/build/reports/lint-results.html


# script:
    # - echo "Travis branch is $TRAVIS_BRANCH"    #Print out which branch it is.
    # - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"    #Print out pull request number.
    # - android-wait-for-emulator             #Run wait for the emulator script.
    # - adb devices                           #Display list of devices
    # - adb shell input keyevent 82 &
    # - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace 

after_success:
    - codecov                       #Run codecov
